### ISSUE TITLE
Print history

### ISSUE THREAD

**Issue by dmvict** [Wandalen/game_chess#107]
Task consists of next steps: 

- Implement method to print moves history.
- Implement command `.moves.history`. Command prints the history of steps. Command accepts no arguments.

After closing the issue, consider closing related task #36.

**Comment by twentyone212121** [comment]
Беру цей тікет
Команда 0xADDC0DE

**Comment by dmvict** [comment]
> Беру цей тікет Команда 0xADDC0DE

Assigned.
