### ISSUE TITLE
Store list of games on the server

### ISSUE THREAD

**Issue by TheBestTvarynka** [Wandalen/game_chess#112]
The task is to implement an in-memory game store.

In our app architecture, every game store implements the `GameStore` trait ( see [`src/store/mod.rs`](https://github.com/Wandalen/game_chess/blob/main/module/server/src/store/mod.rs) ). For now, we decide you use an in-memory store. It means that we save all games in memory (RAM. Just in a vector of the Games).

The file with main code: [`src/store/memory.rs`](https://github.com/Wandalen/game_chess/blob/main/module/server/src/store/memory.rs).

Task consists of next steps: 
- Implement method `add_game`. The method saves game into container.
- Implement method `get_game`. The method iterates over container and gets the game by string id.
- Implement method `get_games`. The method returns reference to own container.
- Implement method `update_game`. The method find a game by the id and replace data from source game.

**Comment by Wandalen** [comment]
Do you suggest to implement a struct? Why can't we use a Vector?

**Comment by TheBestTvarynka** [comment]
Yes, `GameStore` probably will use `Vec` inside

**Comment by kradenkov** [comment]
Cassiopea wants this ticket

**Comment by dmvict** [comment]
> Cassiopea wants this ticket

Асайню

**Comment by NastyaVicodin** [comment]
Taken (Blue Oyster)
