### ISSUE TITLE
Ability to get game state from the server

### ISSUE THREAD

**Issue by TheBestTvarynka** [Wandalen/game_chess#113]
Task consists of next steps: 

- Implement the `read_game_state` method.

Source file is [`src/rpc_server.rs`](https://github.com/Wandalen/game_chess/blob/main/module/server/src/rpc_server.rs).

**Comment by TimpaPumpa** [comment]
Косеопия

**Comment by dmvict** [comment]
> Косеопия

Done

**Comment by TimpaPumpa** [comment]
снять с меня тикет сложно
