### ISSUE TITLE
Ability to forfait in multiplayer

### ISSUE THREAD

**Issue by TheBestTvarynka** [Wandalen/game_chess#114]
Task consists of next steps: 

- Implement the `push_game_gg` method. This method declares forfeit of the player and set the win to the opponent. After it close the game.

Source file is [`src/generated/chess.rs`](https://github.com/Wandalen/game_chess/blob/main/module/multiplayer/src/generated/chess.rs).

**Comment by NastyaVicodin** [comment]
Taken (Blue Oyster)

**Comment by dmvict** [comment]
> Taken (Blue Oyster)

Assigned
