### ISSUE TITLE
Dead games cleaning

### ISSUE THREAD

**Issue by TheBestTvarynka** [Wandalen/game_chess#116]
Task consists of next steps:

- Extend structures that implements multiplayer game and move by field with timestamp of creation ( structures `Game` and `GameMove` ).
- Implement routine to remove inactive game. Consider to setup default inactive time near 1h. 
- Setup server to run routine periodically.

**Comment by ArtemZHR** [comment]
команда: Касиопея

**Comment by dmvict** [comment]
Assingned.

**Comment by kradenkov** [comment]
I'l procced with this task.
BlueOysters team
