### ISSUE TITLE
List of spectators

### ISSUE THREAD

**Issue by TheBestTvarynka** [Wandalen/game_chess#118]
The existed API does not support mechanism of subscription.

Task consists of next steps: 

- Extend structure `Game` to handle list of spectators. 
- Extend API of spectators to subscribe a game. 
- Add method to filter active spectators to the game.
- Implement API method `read_game_spectators`.

**Comment by DenysMiroshnyk** [comment]
I'll take this one
(The Blue Oyster Team)

**Comment by dmvict** [comment]
> I'll take this one (The Blue Oyster Team)

Assingned.
