### ISSUE TITLE
Subscription on result of a game

### ISSUE THREAD

**Issue by TheBestTvarynka** [Wandalen/game_chess#121]
Task consists of next steps: 

- Implement client side method to subscribe on result of the game. 

Consider to use client side requests to the server instead of implementing the mechanism of subscription on the server.

If #118 is implemented, you may extend sever to send result of the game to the client.

**Comment by kradenkov** [comment]
Cassiopea wants this ticket

**Comment by dmvict** [comment]
> Cassiopea wants this ticket

Assigned. 

Please, close some taken issues :)
