### ISSUE TITLE
Use sructures of module core in module multiplayer. 

### ISSUE THREAD

**Issue by TheBestTvarynka** [Wandalen/game_chess#122]
Source file is `core/src/lib.rs`.

Task consists of next steps: 

- Review this code. You can see that we have different structs and enums for our game. 
- To finish them: add needed fields, implement the needed method. 
Pay attention: not all methods signatures are written. You obviously need to add more.

Hint: open `proto/chess_game.proto`. In this file, you can find information about how we see those structures. But do not just repeat them. We are also humans that make mistakes.

**Comment by al-mehedi** [comment]
Hi @dmvict, I would like to work on this issue but it seems `core/src/model.rs` is missing. Will you please assist me?

**Comment by dmvict** [comment]
Hello, @al-mehedi. 

Maybe, the file was changed. Now, it is file [`core/src/lib.rs`](https://github.com/Wandalen/game_chess/blob/master/module/core/src/lib.rs). 

I'll update the task.
