### ISSUE TITLE
Highlight cells under cursor

### ISSUE THREAD

**Issue by dmvict** [Wandalen/game_chess#143]
Depends on issues:

- #45.

Task consists of next steps: 

- Implement the systems to highlight cells ( pieces ) under cursor by different colors.
- Extend the implemented  system to highlight the selected cells.

Feature: 

- Selected cell should higlight when cursor is moving and squares unders cursor should highlight also.

The next samples can be helpful:

- [How to draw board from sprites](https://github.com/Wandalen/game_chess/tree/main/sample/board_draw).

Useful links: 

- [Bevy entities and components](https://bevy-cheatbook.github.io/programming/ec.html).
- [Bevy resources](https://bevy-cheatbook.github.io/programming/res.html).

**Comment by Epsylon42** [comment]
Беру
Команда 0xADDC0DE

**Comment by dmvict** [comment]
Assigned.

**Comment by qarux** [comment]
Take
