### ISSUE TITLE
Load game from FEN

### ISSUE THREAD

**Issue by dmvict** [Wandalen/game_chess#26]
Task consists of next steps: 

- Implement routine that reads game file and deserialize it into strict structure of Game. Take into account that game can contain only FEN string ( #50 ) without history. 
- Implement routine to transform [FEN](https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation) string into chess board.
- Implement command `.game.from.fen`. Command argument - FEN string

**Comment by ihor-tarasov** [comment]
Taken
Babrochky

**Comment by dmvict** [comment]
Assigned.
