### ISSUE TITLE
Save game

### ISSUE THREAD

**Issue by dmvict** [Wandalen/game_chess#27]
*Complexity* : **mid**

Task consists of next steps: 

- Implement interface to transform chess board state to [FEN](https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation) string.
- Implement routine to save file. Note: each file should have unique ID that will be recognizable by user.  
- Implement command `.game.save`. 
- Extend interface of command `.quit`. Ask to save game.

After closing the issue, consider closing related task to [list games](#28) and [load a game](#29)

**Comment by sinnrrr** [comment]
TAKEN

**Comment by sinnrrr** [comment]
Done: https://github.com/Wandalen/game_chess/pull/87
