### ISSUE TITLE
Make a random move

### ISSUE THREAD

**Issue by dmvict** [Wandalen/game_chess#32]
Depends on issues : 
- #31.

Task consists of next steps: 
- Use a routine from #31 to generate list of available steps.
- Get random move from list and apply it to the game.
- Implement command `.move.random`.

**Comment by sinnrrr** [comment]
Taken, Babrochky

**Comment by dmvict** [comment]
> Taken, Babrochky

The task is locked.
Please, resolve task #31 before.

**Comment by olgZZZ** [comment]
I'll take it

**Comment by olgZZZ** [comment]
Done  #273
