### ISSUE TITLE
Declare the forfeit

### ISSUE THREAD

**Issue by dmvict** [Wandalen/game_chess#37]
Task consists of next steps: 

- Implement routine that allows user to declare the forfeit ( leave the game losing game ).
- Implement command `.gg` ( good game ).
- Bind routine to gui `gg` feature if #56 is implemented.
- Extend enum `GameStatus` adding variant `gg`.

Features of command: 

- If user plays with the computer, then routine close the game. 
- If user plays with another user, then routine prints to the opponent about declared forfeit and prints that opponent wins.

**Comment by sinnrrr** [comment]
Taken, Babrochky

**Comment by dmvict** [comment]
Assigned

**Comment by sinnrrr** [comment]
Done: https://github.com/Wandalen/game_chess/pull/162
