### ISSUE TITLE
CRITICAL : Serialization / Deserialization of Game

### ISSUE THREAD

**Issue by Wandalen** [Wandalen/game_chess#40]
*Complexity* : **mid**

Task consists of next steps: 

- Choose the data format ( consider [FEN](https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation) format and JSON for online )
- Implement routine/trait to serialize game state.
- Implement routine/trait to deserialize saved data.

**Comment by volodymyrmigdal** [comment]
TAKEN

**Comment by volodymyrmigdal** [comment]
Done in : https://github.com/Wandalen/game_chess/commit/0be09ad57f88cfe1a309d4f3a6897b395b548999
