### ISSUE TITLE
Board score evaluation

### ISSUE THREAD

**Issue by volodymyrmigdal** [Wandalen/game_chess#41]
Task consists of next steps: 

- Implement method `score` in `Board` that evaluates score of current state of the board
- Extend command `.status` to print score.

See [example](https://github.com/Wandalen/game_chess/tree/main/sample/core_board_score).

Resources:

- [Pleco](https://docs.rs/pleco/0.5.0/pleco/)
- [Board](https://docs.rs/pleco/0.5.0/pleco/board/struct.Board.html)
- [bitboard-representation](https://docs.rs/pleco/latest/pleco/board/struct.Board.html#bitboard-representation)
- [eval_low](https://docs.rs/pleco/0.5.0/pleco/tools/eval/struct.Eval.html#method.eval_low)
- [Algorithms Explained – minimax and alpha-beta pruning](https://youtu.be/l-hh51ncgDI)

The board score value:
![score](https://user-images.githubusercontent.com/11973342/147363138-49b9c518-eea5-4cab-9134-d03ae067513c.png)

**Comment by 26letterz** [comment]
Taken

**Comment by dmvict** [comment]
> Taken

Please, add team name before.

**Comment by 26letterz** [comment]
Babrochky

**Comment by dmvict** [comment]
Assigned.
