### ISSUE TITLE
Draw pieces

### ISSUE THREAD

**Issue by Wandalen** [Wandalen/game_chess#44]
Task consists of next steps: 

- Choose the pieces assets ( [example](https://github.com/Wandalen/game_chess/blob/main/sample/sprite_partial/assets/icons.png) ).
- Extend startup routine. Load pieces as resource.
- Extend system for board drawing. For positioning use structure `PieceLocations`.

The next samples can be helpful:

- [How to draw sprite from image](https://github.com/Wandalen/game_chess/tree/main/sample/sprite).
- [How to draw sprite from part of image](https://github.com/Wandalen/game_chess/blob/main/sample/sprite_partial).

Useful links: 

- [Bevy entities and components](https://bevy-cheatbook.github.io/programming/ec.html).
- [Bevy resources](https://bevy-cheatbook.github.io/programming/res.html).

**Comment by tlond** [comment]
візму тікет

**Comment by volodymyrmigdal** [comment]
Taken

**Comment by volodymyrmigdal** [comment]
Done in: https://github.com/Wandalen/game_chess/pull/188
