### ISSUE TITLE
Highlight cells

### ISSUE THREAD

**Issue by Wandalen** [Wandalen/game_chess#45]
Task consists of next steps: 

- Implement a **function** that creates cell entities of provided color.

The next samples can be helpful:

- [How to draw board from sprites](https://github.com/Wandalen/game_chess/tree/main/sample/board_draw).

After closing the issue, consider closing related task:
- #46.
- #47.

Useful links: 

- [Bevy entities and components](https://bevy-cheatbook.github.io/programming/ec.html).
- [Bevy resources](https://bevy-cheatbook.github.io/programming/res.html).

**Comment by LastSymbol0** [comment]
Hey, I'll take this task

**Comment by Wandalen** [comment]
How to add new sprite from a function?

**Comment by dmvict** [comment]
```rs
commands.spawn_bundle( SpriteBundle { ... });
```

Or, give me details, please.

**Comment by Wandalen** [comment]
```
fn f1( x : i32 )
{
  /* we want to add new sprite from here */
}
```

**Comment by dmvict** [comment]
You need to have commands instance. 

It is [an example](https://github.com/Wandalen/game_chess/blob/main/module/sample_gui_with_board/src/draw.rs#L159)

**Comment by Wandalen** [comment]
```rust
use bevy_ecs::world::World;

struct Position {
  x: f32,
  y: f32,
}

let mut world = World::new();
let entity = world.spawn()
    .insert(Position { x: 0.0, y: 0.0 })
    .id();

let position = world.entity(entity).get::<Position>().unwrap();
assert_eq!(position.x, 0.0);
```

**Comment by Epsylon42** [comment]
Беру
Команда 0xADDC0DE

**Comment by dmvict** [comment]
Assingned.
