### ISSUE TITLE
Implement sound system

### ISSUE THREAD

**Issue by Wandalen** [Wandalen/game_chess#52]
Task consists of next steps: 

- Extend setup system to load sound assets. 
- Put you audio files into directory `assets/sound` in the root of module `game`.
- Implement events handling in the module.

Feature: 
 
- Sound for move.
- Sound for draw.
- Sound for lose/win.

The next samples can be helpful:

- [World events](https://github.com/bevyengine/bevy/blob/e74f7a7335e66199a55b443c872dee23cbf03dc7/crates/bevy_ecs/examples/events.rs).

Useful links: 

- [Bevy assets](https://bevy-cheatbook.github.io/features/assets.html).
- [Bevy events](https://bevy-cheatbook.github.io/programming/events.html).

**Comment by FervorousGremlin** [comment]
Беру тикет
Команда 0xADDC0DE

**Comment by dmvict** [comment]
Assigned. 

Consider to close some issues.
