### ISSUE TITLE
Implement GUI for main menu

### ISSUE THREAD

**Issue by Wandalen** [Wandalen/game_chess#53]
Task consists of next steps: 

- Investigate the game shared resources and check access to it ( colors, sound ).
- Implement system with GUI interface drawing.
- Bind menu to corresponding features if them are implemented.

Note. The GUI can have a form whatever you want. Maybe, simplest way is to use static side panel (  [sample with static panel](https://github.com/Wandalen/game_chess/tree/main/sample/gui_with_board) ). The game board should be locked.

Feature: 

- Button for start new game.
- Button for start new game with AI.
- Button for multiplayer.
- GUI for options ( color schema, sound on/off ).
- Button for quit.

The next samples can be helpful:

- [How to add simple GUI](https://github.com/Wandalen/game_chess/tree/main/sample/simple_gui).

Useful links: 

- [Bevy states](https://bevy-cheatbook.github.io/programming/states.html).
- [Bevy events](https://bevy-cheatbook.github.io/programming/events.html).

**Comment by Keep-Simple** [comment]
Taken, Babrocky

**Comment by dmvict** [comment]
Assigned.

**Comment by qarux** [comment]
Take
