### ISSUE TITLE
Cusom color schema

### ISSUE THREAD

**Issue by Wandalen** [Wandalen/game_chess#54]
Task consists of next steps: 

* Implement system that changes color of cells.
  - Implement routine that change the game gamma. 
  - Implement GUI that change gamma.

Feature: 
 
- For each cells type should be its own picker. 

The next samples can be helpful:

- [How to add GUI with usable combobox](https://github.com/Wandalen/game_chess/tree/main/sample/gui_with_board).

Useful links: 

- [Bevy resources](https://bevy-cheatbook.github.io/programming/res.html).
- [Bevy events](https://bevy-cheatbook.github.io/programming/events.html).

**Comment by 26letterz** [comment]
Babrochky, taken

**Comment by dmvict** [comment]
Assigned.

**Comment by qarux** [comment]
Done #257
