### ISSUE TITLE
Turns ( moves ) in graphics

### ISSUE THREAD

**Issue by Wandalen** [Wandalen/game_chess#57]
Task consists of next steps: 

* Implement system that handle mouse events on the board.
  - Click.
  - Move.
* Implement logic for operations with pieces ( except highlighting ).

Feature: 

- The interface should use common API with the CLI interface to make moves.

The next samples can be helpful:

- [Detection of mouse events](https://github.com/Wandalen/game_chess/tree/main/sample/mouse_event_detection)

**Comment by mvlabat** [comment]
Taking this one (The Blue Oyster)

**Comment by dmvict** [comment]
Assigned.
