### ISSUE TITLE
Improve board output

### ISSUE THREAD

**Issue by volodymyrmigdal** [Wandalen/game_chess#68]
*Complexity* : **mid**

Task consists of next steps: 

- Extend `Board.print()` method to draw [ranks](https://www.chess.com/terms/chessboard#ranks) and [files](https://www.chess.com/terms/chessboard#files), similar to:
```
8 | 56 57 58 59 60 61 62 63
7 | 48 49 50 51 52 53 54 55
6 | 40 41 42 43 44 45 46 47
5 | 32 33 34 35 36 37 38 39
4 | 24 25 26 27 28 29 30 31
3 | 16 17 18 19 20 21 22 23
2 | 8  9  10 11 12 13 14 15
1 | 0  1  2  3  4  5  6  7
  -------------------------
     a  b  c  d  e  f  g  h
```

Note. The numbers 0-63 will be replaced by board output. 

The next samples can be helpful:

- [Create simple chess game](https://github.com/Wandalen/game_chess/tree/main/module/sample_core_chess_game)

**Comment by n-romaniv** [comment]
Taken

**Comment by n-romaniv** [comment]
Done

**Comment by dmvict** [comment]
> Done

Good work!
