### ISSUE TITLE
Add aliases for commands

### ISSUE THREAD

**Issue by volodymyrmigdal** [Wandalen/game_chess#69]
*Complexity* : **low**

Extend [CLI](https://github.com/Wandalen/game_chess/blob/main/module/cli/src/main.rs) module to introduce aliases for commands:

- `.s` -> `.status`
- `.m` -> `.move`

Change [CLI main file](https://github.com/Wandalen/game_chess/blob/main/module/cui/src/main.rs) to add new command aliases.

Also, you can propose new command aliases and if it will be approved, then add it to CLI.

**Comment by artemhlezin** [comment]
!

**Comment by dmvict** [comment]
Good work!
