### ISSUE TITLE
Board margins

### ISSUE THREAD

**Issue by Wandalen** [Wandalen/game_chess#76]
Tweak the camera to get expected results.

Task consists of next steps: 

- Investigate how to work the camera projection.
- Add offsets in the camera projection.
- Implement system that draws margins around board.
- Add system to the Bevy main app.

Feature:

- Board should not go outside window neither touch edges of window.
- To avoid that introduce parameter during drawing, number of cells for gap between board and window edge.

![image](https://user-images.githubusercontent.com/7414255/147377486-43a424d9-90ee-46fc-a3f0-69a9f8cb2478.png)

The next samples can be helpful:

- [How to draw board from sprites](https://github.com/Wandalen/game_chess/tree/main/sample/board_draw).
- [How to draw sprite from image](https://github.com/Wandalen/game_chess/tree/main/sample/sprite).

**Comment by ihor-tarasov** [comment]
Taken

**Comment by dmvict** [comment]
> Taken

Please, add name of command.

**Comment by ihor-tarasov** [comment]
Babrochky

**Comment by dmvict** [comment]
Assigned.
